version: '3'
services:
  app:
    image: cicd102
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_USERNAME=jing
      - MONGODB_PASSWORD=7KyPFpwR8GQu1fvd
      - MONGODB_DATABASE
      # - MONGODB_CONNECTION_STRING=mongodb://mongo/cicd201
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./src:/app/src
